apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
      annotations: {}
    spec:
      containers:
        - name: ratelimit
          # image: ratelimit-renuka:master
          image: envoyproxy/ratelimit:9d8d70a8
          # image: envoyproxy/ratelimit:ac270a10
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/ratelimit"
          env:
            - name: USE_STATSD
              value: "false" # TODO: false
            - name: LOG_LEVEL
              value: info # debug
            - name: REDIS_SOCKET_TYPE
              value: tcp
            - name: REDIS_TYPE
              # value: sentinel
              value: cluster
            - name: REDIS_URL
              # value: redis:6379 # TODO: update service name
              # value: "mymaster,cc-redis-node-0:26379,cc-redis-node-1:26379" # TODO: update service name
              value: "redis-cluster:6379"
            - name: REDIS_PIPELINE_LIMIT
              value: "8"
            - name: REDIS_AUTH
              value: "password123"
            - name: RUNTIME_ROOT
              value: /data
            - name: RUNTIME_SUBDIRECTORY
              value: ratelimit
            - name: RUNTIME_WATCH_ROOT
              value: "false"
            - name: LOCAL_CACHE_SIZE_IN_BYTES
              value: "524288"
            - name: LIMIT_RESPONSE_HEADERS_ENABLED
              value: "false"
            - name: GRPC_SERVER_USE_TLS
              value: "true"
            - name: GRPC_SERVER_TLS_CERT
              value: "/etc/ratelimit/security/mg.pem"
            - name: GRPC_SERVER_TLS_KEY
              value: "/etc/ratelimit/security/mg.key"
            - name: GRPC_CLIENT_TLS_CACERT
              value: "/etc/ratelimit/security/mg.pem"
            - name: GRPC_CLIENT_TLS_SAN
              value: "localhost"
          volumeMounts:
            - mountPath: /data/ratelimit/config/ratelimit-config.yaml
              name: ratelimit-config-vol
              subPath: ratelimit-config.yaml
            - mountPath: /etc/ratelimit/security/mg.pem
              name: ratelimit-certs-vol
              subPath: mg.pem
            - mountPath: /etc/ratelimit/security/mg.key
              name: ratelimit-certs-vol
              subPath: mg.key
          resources:
            requests:
              memory: "1Gi"
              cpu: "2000m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
          ports:
            - containerPort: 8081 # gRPC
            - containerPort: 8080 # HTTP JSON
            - containerPort: 6070 # debug
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthcheck
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthcheck
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 5
      volumes:
        - name: ratelimit-config-vol
          configMap:
            name: ratelimit-config
        - name: ratelimit-certs-vol
          secret:
            secretName: ratelimit-certs
      restartPolicy: Always
