apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratelimit
  name: ratelimit
spec:
  type: ClusterIP
  selector:
    app: ratelimit
  ports:
    - name: "http-grpc"
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: "http-json"
      port: 8080
      targetPort: 8080
      protocol: TCP
