apiVersion: apps/v1
kind: Deployment
metadata:
  name: choreo-connect-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: choreo-connect-adapter
  template:
    metadata:
      labels:
        app: choreo-connect-adapter
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: choreo-connect-adapter
          image: renukafernando/choreo-connect-adapter:1.1.0-ratelimit-patch
          imagePullPolicy: IfNotPresent
          env:
            - name: ADAPTER_PRIVATE_KEY_PATH
              value: "/home/wso2/security/keystore/mg.key"
            - name: ADAPTER_PUBLIC_CERT_PATH
              value: "/home/wso2/security/keystore/mg.pem"
            - name: cp_admin_pwd
              value: "admin"
            - name: adapter_admin_pwd
              value: "admin"
          volumeMounts:
            - mountPath: /home/wso2/security/keystore
              name: adapter-keystore-vol
            - mountPath: /home/wso2/security/truststore
              name: adapter-truststore-vol
            - mountPath: /home/wso2/security/truststore/consul
              name: consul-certs-vol
            - mountPath: /home/wso2/conf/config.toml
              subPath: config.toml
              name: config-toml-vol
            - mountPath: /home/wso2/conf/log_config.toml
              subPath: log_config.toml
              name: logconfig-toml-vol
            - mountPath: /home/wso2/artifacts/apis
              name: api-artifacts-vol
          resources:
            # requests:
            #   memory: "300Mi"
            #   cpu: "300m"
            # limits:
            #   memory: "300Mi"
            #   cpu: "300m"
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 18000
            - containerPort: 9843
          livenessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: 8
            periodSeconds: 5
      volumes:
        - name: adapter-keystore-vol
          secret:
            secretName: adapter-keystore
        - name: adapter-truststore-vol
          secret:
            secretName: adapter-truststore
        - name: consul-certs-vol
          secret:
            secretName: consul-certs
        - name: config-toml-vol
          configMap:
            name: config-toml
        - name: log4j2-vol
          configMap:
            name: log4j2
        - name: logconfig-toml-vol
          configMap:
            name: logconfig-toml
        - name: api-artifacts-vol
          emptyDir: {}
      restartPolicy: Always
