apiVersion: v1
kind: Service
metadata:
  labels:
    app: choreo-connect-adapter
  name: adapter
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-subnet"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.224.1.2
  selector:
    app: choreo-connect-adapter
  ports:
    - name: "http-adaptermanagementserver"
      port: 18000
      targetPort: 18000
      protocol: TCP
    - name: "https-adapter"
      port: 9843
      targetPort: 9843
      protocol: TCP
