[ratelimit]
domain = "default"
stage = 0
requestType = "external"
failureModeDeny = false
rateLimitedAsResourceExhausted = false
disableXEnvoyRatelimitedHeader = false
enableXRatelimitHeaders = 1
  [ratelimit.rateLimitService.grpcService.timeout]
  seconds = 20
  
  [ratelimit.rateLimitService]
  transportApiVersion = 2

  [ratelimit.timeout]
  seconds = 0
  nanos = 80000000


[adapter]
[adapter.server]
    enabled = true
    port = "9843"
    tokenPrivateKeyPath = "/home/wso2/security/keystore/mg.key"
    [[adapter.server.users]]
    username = "admin"
    password = "$env{adapter_admin_pwd}"

# default vhosts mapping for standalone mode
[[adapter.vhostMapping]]
    environment = "Default"
    vhost = "cc-envoy"

[adapter.keystore]
    certPath = "/home/wso2/security/keystore/mg.pem"
    keyPath = "/home/wso2/security/keystore/mg.key"

[adapter.truststore]
    location = "/home/wso2/security/truststore"

[router]
    listenerPort = 9090
    securedListenerPort = 9095
    systemHost = "cc-envoy"

[router.keystore]
    certPath = "/home/wso2/security/keystore/mg.pem"
    keyPath = "/home/wso2/security/keystore/mg.key"

[router.upstream]
[router.upstream.tls]
    trustedCertPath = "/etc/ssl/certs/ca-certificates.crt"
    verifyHostName = true
    disableSslVerification = false

[enforcer]
[enforcer.jwtIssuer]
    enabled = true
    issuer = "https://cc-envoy/testkey"

[enforcer.security]
[[enforcer.security.tokenService]]
    name = "Resident Key Manager"
    issuer = "https://apim.wso2.com/oauth2/token"
    certificateAlias = "wso2carbon"
    jwksURL = ""
    validateSubscription = false
    consumerKeyClaim = "azp"
    certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

[[enforcer.security.tokenService]]
    name = "MGW"
    issuer = "https://cc-envoy/testkey"
    certificateAlias = "mgw"
    jwksURL = ""
    validateSubscription = false
    consumerKeyClaim = ""
    certificateFilePath = "/home/wso2/security/truststore/mg.pem"

[[enforcer.security.tokenService]]
    name = "APIM Publisher"
    issuer = "https://apim.wso2.com/publisher"
    validateSubscription = true
    certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

[enforcer.throttling]
    enableGlobalEventPublishing = false
    jmsConnectionProviderURL = "amqp://admin:$env{tm_admin_pwd}@carbon/carbon?brokerlist='tcp://apim:5672'"
    [enforcer.throttling.publisher]
    username = "admin"
    password = "$env{tm_admin_pwd}"
    [[enforcer.throttling.publisher.URLGroup]]
        receiverURLs = ["tcp://apim:9611"]
        authURLs = ["ssl://apim:9711"]

[analytics]
    enabled = false

[enforcer.metrics]
    enabled = false
