---
domain: default
descriptors:
  - key: org
    value: John
    descriptors:
      - key: vhost
        value: cc-envoy
        descriptors:
          # API level policy
          - key: resource # api: /petstore/v1    resource: /petstore/v1/findById
            descriptors:
              - key: method # method: [ALL|GET|PUT|POST...] (ALL for API level and resource level)
                descriptors:
                  - key: policy
                    value: 3PerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 3
                      - key: condition
                        value: c1 # we may have to use a UUID instead of C1, C2, ...
                        rate_limit:
                          unit: minute
                          requests_per_unit: 5
                      - key: condition
                        value: c2
                        rate_limit:
                          unit: minute
                          requests_per_unit: 10

      # Subscription level
      - key: subscription # Sends from ext auth service as a header
        descriptors:
          - key: policy
            value: 3PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 3
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 1
          - key: policy
            value: 5PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 5
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 1

      # Application level
      - key: application # Sends from ext auth service as a header
        descriptors:
          - key: policy
            value: 3PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 3
