---
domain: default
descriptors:
  - key: org
    value: John
    descriptors:
      - key: vhost
        value: cc-envoy
        descriptors:
          # API level policy
          - key: resource # api: /petstore/v1    resource: /petstore/v1/findById
            descriptors:
              - key: method # method: [ALL|GET|PUT|POST...] (ALL for API level and resource level)
                descriptors:
                  - key: policy
                    value: 20KPerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 20000
                      - key: condition
                        value: c1 # we may have to use a UUID instead of C1, C2, ...
                        rate_limit:
                          unit: hour
                          requests_per_unit: 20000
                  - key: policy
                    value: 1500PerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 150
                      - key: condition
                        value: c1 # we may have to use a UUID instead of C1, C2, ...
                        rate_limit:
                          unit: minute
                          requests_per_unit: 300
                  - key: policy
                    value: 18000PerHour
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: hour
                          requests_per_unit: 18000
                  - key: policy
                    value: 500PerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 500
                  - key: policy
                    value: 600PerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 600
                      - key: condition
                        value: c1 # we may have to use a UUID instead of C1, C2, ...
                        rate_limit:
                          unit: minute
                          requests_per_unit: 300
                      - key: condition
                        value: c2 # we may have to use a UUID instead of C1, C2, ...
                        rate_limit:
                          unit: minute
                          requests_per_unit: 500
                  - key: policy
                    value: 250PerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 250
                      - key: condition
                        value: c1 # we may have to use a UUID instead of C1, C2, ...
                        rate_limit:
                          unit: minute
                          requests_per_unit: 600
                  - key: policy
                    value: 5MPerMin
                    descriptors:
                      - key: condition
                        value: default
                        rate_limit:
                          unit: minute
                          requests_per_unit: 5000000

      # Subscription level
      - key: subscription # Sends from ext auth service as a header
        descriptors:
          - key: policy
            value: 400PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 400
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 100
          - key: policy
            value: 300PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 300
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 50
          - key: policy
            value: 2000PerHour
            rate_limit:
              unit: hour
              requests_per_unit: 2000
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 50
          - key: policy
            value: 100PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 100
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 10
          - key: policy
            value: 80PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 80
          - key: policy
            value: 5KPerMin
            rate_limit:
              unit: minute
              requests_per_unit: 600
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 50
          - key: policy
            value: 1KPerMin
            rate_limit:
              unit: minute
              requests_per_unit: 600
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 10
          - key: policy
            value: 7MPerMin
            rate_limit:
              unit: minute
              requests_per_unit: 7000000
            descriptors:
              - key: spike
                value: true
                rate_limit:
                  unit: second
                  requests_per_unit: 1000000

      # Application level
      - key: application # Sends from ext auth service as a header
        descriptors:
          - key: policy
            value: 100PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 100
          - key: policy
            value: 9000PerHour
            rate_limit:
              unit: hour
              requests_per_unit: 9000
          - key: policy
            value: 5PerSec
            rate_limit:
              unit: second
              requests_per_unit: 5
          - key: policy
            value: 30PerMin
            rate_limit:
              unit: minute
              requests_per_unit: 30
          - key: policy
            value: 6MPerMin
            rate_limit:
              unit: minute
              requests_per_unit: 6000000
