resources:
  - gateway-runtime
  - ratelimit
  - netty-backend
  # - mock-backend

replicas:
  - name: gateway-runtime
    count: 2
  - name: netty-backend
    count: 1
  # - name: mock-backend
  #   count: 2
  - name: ratelimit
    count: 2
