resources:
  - gateway-runtime
  - ratelimit
  - mock-backend

replicas:
  - name: cc-envoy
    count: 1
  - name: cc-ext-auth
    count: 1
  - name: mock-backend
    count: 1
  - name: ratelimit
    count: 1
